"""Prototype interfaces for the thesis coordination framework."""

from .a2a_adapter import A2AAdapter, AuthorizationError
from .agent_registry import AgentRegistry, EtcdAgentRegistry, InMemoryAgentRegistry, RegisteredAgent
from .admission import (
    AgentAdmissionError,
    AgentAdmissionPolicy,
    CredentialProvider,
    StaticCredentialProvider,
)
from .auxiliary import BoundedAuxiliaryCapabilityFactory
from .coordination_agent import CoordinationAgent
from .coordination_ledger import (
    CoordinationSessionState,
    InMemoryCoordinationLedger,
    JsonlCoordinationLedger,
    LedgerEvent,
    RetryPolicy,
)
from .coordination_sdk import CoordinationSdk, RemoteRegistryError
from .coordination_store import (
    CoordinationStoreError,
    JsonlCoordinationStore,
    LeaseConflictError,
    PostgresCoordinationStore,
    StaleFenceError,
    StoreInvariantError,
)
from .etcd_client import (
    EtcdClient,
    EtcdError,
    EtcdQuorumUnavailableError,
    EtcdUnavailableError,
)
from .etcd_store import EtcdCoordinationStore
from .feasibility import FeasibilityAnalyzer
from .lingo_coordinator import CoordinatorState, LingoLinguisticCoordinator
from .trace_validation import TraceValidationReport, validate_trace
from .models import (
    AgentRegistryEntry,
    CapabilityRequirement,
    CompletionContract,
    ConstraintSpec,
    CoordinationPlanResult,
    CoordinationRunResult,
    FeasibilityReport,
    DraftRequirementSelection,
    HydrationIssue,
    LinguisticPlanDraft,
    GeneratedNlpAgentSpec,
    LeaseRecord,
    PlanGeneration,
    PredicateEvidence,
    ProblemRequest,
    SolutionProposal,
    SessionState,
    TaskAttemptRecord,
    TaskCommitment,
    TaskExecutionResult,
    TaskState,
    TerminalResultRecord,
    TaskSpec,
    TraceEvent,
    ValidationContract,
)
from .plan_hydration import PlanHydrationResult, PlanHydrator
from .semantic_admission import (
    ArtifactContractOption,
    CapabilityCatalogEntry,
    OpenAICompatibleSemanticInterpreter,
    SemanticAdmissionIssue,
    SemanticAdmissionResult,
    SemanticCatalog,
    SemanticGoalSelection,
    SemanticIntentOutput,
    SemanticInterpretationResult,
    SemanticRequestAdmitter,
    TrustPolicyOption,
    semantic_intent_schema,
)
from .semantic_admission_v08 import (
    GoalOverrideV08,
    GroundedSemanticSelection,
    OpenAICompatibleSemanticInterpreterV08,
    RequestSpan,
    RetrievalCandidate,
    SemanticAdmissionIssueV08,
    SemanticAdmissionResultV08,
    SemanticIntentV08,
    SemanticInterpretationResultV08,
    SemanticRequestAdmitterV08,
    SemanticRetrievalResult,
    classify_request_spans,
    evidence_fragments_v08,
    materialize_wire_intent_v08,
    normalize_v08,
    retrieve_semantic_candidates,
    semantic_intent_schema_v08,
    semantic_prompt_v08,
)
from .symbolic_plan_compiler import (
    PlanCompilationDiagnostics,
    PlanCompilationIssue,
    PlanCompilationResult,
    SymbolicPlanCompiler,
)
from .runtime_policies import (
    DurableTraceEvidencePolicy,
    EphemeralTraceEvidencePolicy,
    StrictAuxiliaryAdmissionPolicy,
    StrictDependencyDispatchPolicy,
    SingleUseAuxiliaryLifecyclePolicy,
    UnsafeIgnoreDependencyPolicy,
    UnsafePermissiveAuxiliaryPolicy,
    UnsafeReusableAuxiliaryLifecyclePolicy,
)

__all__ = [
    "A2AAdapter",
    "AgentAdmissionError",
    "AgentAdmissionPolicy",
    "AgentRegistryEntry",
    "AgentRegistry",
    "AuthorizationError",
    "ArtifactContractOption",
    "BoundedAuxiliaryCapabilityFactory",
    "CapabilityRequirement",
    "CapabilityCatalogEntry",
    "CompletionContract",
    "ConstraintSpec",
    "CoordinationAgent",
    "CoordinationSessionState",
    "CoordinationPlanResult",
    "CoordinationRunResult",
    "CoordinationSdk",
    "CoordinatorState",
    "CoordinationStoreError",
    "CredentialProvider",
    "FeasibilityAnalyzer",
    "FeasibilityReport",
    "DraftRequirementSelection",
    "EtcdClient",
    "EtcdAgentRegistry",
    "EtcdCoordinationStore",
    "EtcdError",
    "EtcdQuorumUnavailableError",
    "EtcdUnavailableError",
    "HydrationIssue",
    "GeneratedNlpAgentSpec",
    "GoalOverrideV08",
    "GroundedSemanticSelection",
    "InMemoryCoordinationLedger",
    "InMemoryAgentRegistry",
    "JsonlCoordinationLedger",
    "JsonlCoordinationStore",
    "LedgerEvent",
    "LeaseConflictError",
    "LeaseRecord",
    "LingoLinguisticCoordinator",
    "LinguisticPlanDraft",
    "PlanHydrationResult",
    "PlanHydrator",
    "PlanCompilationDiagnostics",
    "PlanCompilationIssue",
    "PlanCompilationResult",
    "PlanGeneration",
    "PredicateEvidence",
    "ProblemRequest",
    "PostgresCoordinationStore",
    "RemoteRegistryError",
    "RegisteredAgent",
    "RetryPolicy",
    "SemanticAdmissionIssue",
    "SemanticAdmissionResult",
    "SemanticCatalog",
    "SemanticGoalSelection",
    "SemanticIntentOutput",
    "SemanticInterpretationResult",
    "SemanticRequestAdmitter",
    "SessionState",
    "SolutionProposal",
    "StaleFenceError",
    "StaticCredentialProvider",
    "SymbolicPlanCompiler",
    "StoreInvariantError",
    "TaskAttemptRecord",
    "TaskCommitment",
    "TaskExecutionResult",
    "TaskState",
    "TaskSpec",
    "TerminalResultRecord",
    "TraceEvent",
    "TraceValidationReport",
    "ValidationContract",
    "TrustPolicyOption",
    "OpenAICompatibleSemanticInterpreter",
    "OpenAICompatibleSemanticInterpreterV08",
    "RequestSpan",
    "RetrievalCandidate",
    "SemanticAdmissionIssueV08",
    "SemanticAdmissionResultV08",
    "SemanticIntentV08",
    "SemanticInterpretationResultV08",
    "SemanticRequestAdmitterV08",
    "SemanticRetrievalResult",
    "classify_request_spans",
    "evidence_fragments_v08",
    "materialize_wire_intent_v08",
    "normalize_v08",
    "retrieve_semantic_candidates",
    "semantic_intent_schema",
    "semantic_intent_schema_v08",
    "semantic_prompt_v08",
    "validate_trace",
    "DurableTraceEvidencePolicy",
    "EphemeralTraceEvidencePolicy",
    "StrictAuxiliaryAdmissionPolicy",
    "StrictDependencyDispatchPolicy",
    "SingleUseAuxiliaryLifecyclePolicy",
    "UnsafeIgnoreDependencyPolicy",
    "UnsafePermissiveAuxiliaryPolicy",
    "UnsafeReusableAuxiliaryLifecyclePolicy",
]
