"""Prototype interfaces for the thesis coordination framework."""

from .a2a_adapter import A2AAdapter, AuthorizationError
from .agent_registry import AgentRegistry, EtcdAgentRegistry, InMemoryAgentRegistry, RegisteredAgent
from .admission import (
    AgentAdmissionError,
    AgentAdmissionPolicy,
    CredentialProvider,
    StaticCredentialProvider,
)
from .auxiliary import BoundedAuxiliaryCapabilityFactory
from .coordination_agent import CoordinationAgent
from .coordination_ledger import (
    CoordinationSessionState,
    InMemoryCoordinationLedger,
    JsonlCoordinationLedger,
    LedgerEvent,
    RetryPolicy,
)
from .coordination_sdk import CoordinationSdk, RemoteRegistryError
from .coordination_store import (
    CoordinationStoreError,
    JsonlCoordinationStore,
    LeaseConflictError,
    PostgresCoordinationStore,
    StaleFenceError,
    StoreInvariantError,
)
from .etcd_client import (
    EtcdClient,
    EtcdError,
    EtcdQuorumUnavailableError,
    EtcdUnavailableError,
)
from .etcd_store import EtcdCoordinationStore
from .feasibility import FeasibilityAnalyzer
from .lingo_coordinator import CoordinatorState, LingoLinguisticCoordinator
from .trace_validation import TraceValidationReport, validate_trace
from .models import (
    AgentRegistryEntry,
    CapabilityRequirement,
    CompletionContract,
    ConstraintSpec,
    CoordinationPlanResult,
    CoordinationRunResult,
    FeasibilityReport,
    DraftRequirementSelection,
    HydrationIssue,
    LinguisticPlanDraft,
    GeneratedNlpAgentSpec,
    LeaseRecord,
    PlanGeneration,
    PredicateEvidence,
    ProblemRequest,
    SolutionProposal,
    SessionState,
    TaskAttemptRecord,
    TaskCommitment,
    TaskExecutionResult,
    TaskState,
    TerminalResultRecord,
    TaskSpec,
    TraceEvent,
    ValidationContract,
)
from .plan_hydration import PlanHydrationResult, PlanHydrator
from .runtime_policies import (
    DurableTraceEvidencePolicy,
    EphemeralTraceEvidencePolicy,
    StrictAuxiliaryAdmissionPolicy,
    StrictDependencyDispatchPolicy,
    SingleUseAuxiliaryLifecyclePolicy,
    UnsafeIgnoreDependencyPolicy,
    UnsafePermissiveAuxiliaryPolicy,
    UnsafeReusableAuxiliaryLifecyclePolicy,
)

__all__ = [
    "A2AAdapter",
    "AgentAdmissionError",
    "AgentAdmissionPolicy",
    "AgentRegistryEntry",
    "AgentRegistry",
    "AuthorizationError",
    "BoundedAuxiliaryCapabilityFactory",
    "CapabilityRequirement",
    "CompletionContract",
    "ConstraintSpec",
    "CoordinationAgent",
    "CoordinationSessionState",
    "CoordinationPlanResult",
    "CoordinationRunResult",
    "CoordinationSdk",
    "CoordinatorState",
    "CoordinationStoreError",
    "CredentialProvider",
    "FeasibilityAnalyzer",
    "FeasibilityReport",
    "DraftRequirementSelection",
    "EtcdClient",
    "EtcdAgentRegistry",
    "EtcdCoordinationStore",
    "EtcdError",
    "EtcdQuorumUnavailableError",
    "EtcdUnavailableError",
    "HydrationIssue",
    "GeneratedNlpAgentSpec",
    "InMemoryCoordinationLedger",
    "InMemoryAgentRegistry",
    "JsonlCoordinationLedger",
    "JsonlCoordinationStore",
    "LedgerEvent",
    "LeaseConflictError",
    "LeaseRecord",
    "LingoLinguisticCoordinator",
    "LinguisticPlanDraft",
    "PlanHydrationResult",
    "PlanHydrator",
    "PlanGeneration",
    "PredicateEvidence",
    "ProblemRequest",
    "PostgresCoordinationStore",
    "RemoteRegistryError",
    "RegisteredAgent",
    "RetryPolicy",
    "SessionState",
    "SolutionProposal",
    "StaleFenceError",
    "StaticCredentialProvider",
    "StoreInvariantError",
    "TaskAttemptRecord",
    "TaskCommitment",
    "TaskExecutionResult",
    "TaskState",
    "TaskSpec",
    "TerminalResultRecord",
    "TraceEvent",
    "TraceValidationReport",
    "ValidationContract",
    "validate_trace",
    "DurableTraceEvidencePolicy",
    "EphemeralTraceEvidencePolicy",
    "StrictAuxiliaryAdmissionPolicy",
    "StrictDependencyDispatchPolicy",
    "SingleUseAuxiliaryLifecyclePolicy",
    "UnsafeIgnoreDependencyPolicy",
    "UnsafePermissiveAuxiliaryPolicy",
    "UnsafeReusableAuxiliaryLifecyclePolicy",
]
